/*
 * Copyright(C) Triniforce
 * All Rights Reserved.
 *
 */ 
package com.triniforce.postoffice.intf;

import java.util.Map;

/**
 * Map<Name, GUID> of boxes in given StreetPath. GUID is generated by system and unique for each box.
 */
public class LTRGetBoxes extends LTRGet<Map<String, String>>{
    private StreetPath m_streetPath;

    public LTRGetBoxes(){
        
    }
    
    public LTRGetBoxes(StreetPath streetPath) {
        super();
        setStreetPath(streetPath);
    }

    public StreetPath getStreetPath() {
        return m_streetPath;
    }

    public void setStreetPath(StreetPath streetPath) {
        m_streetPath = streetPath;
    }    
}
