/*
 * Copyright(C) Triniforce
 * All Rights Reserved.
 *
 */ 
package com.triniforce.postoffice.intf;

import java.util.Map;
import java.util.UUID;

/**
 * Map<Name, UUID> of boxes in given StreetPath. GUID is generated by system and unique for each box.
 */
public class LTRListBoxes extends LTRGet<Map<String, UUID>>{
    private StreetPath m_streetPath;

    public LTRListBoxes(){
        
    }
    
    public LTRListBoxes(StreetPath streetPath) {
        super();
        setStreetPath(streetPath);
    }

    public StreetPath getStreetPath() {
        return m_streetPath;
    }

    public void setStreetPath(StreetPath streetPath) {
        m_streetPath = streetPath;
    }    
}
